### ISSUE TITLE
Issue when installing on Linux (Manjaro 18.0.4)

### ISSUE THREAD

**Issue by vincentdupaquis** [Ledger-Donjon/lascar#10]
Hello,

When installing on Linux, we had issues during install.
It appears that the command "python3 setup.py install --user" was not sufficient, and that we had to go for a "sudo python3 setup.py install". Running it with "sudo python3 setup.py install --user" was the cause of the issue.

Regards,
Vincent.

**Comment by manuelsanpedro** [comment]
Hello,

Please indicate the output of your `python3 setup.py install --user` so that we can investigate.

Best

**Comment by manuelsanpedro** [comment]
I think that indeed `sudo python3 setup.py install --user` was the problem.

This command creates files into your home directory with root permission.

But, if you run after a simple `python3 setup.py install --user`, you will try to modify those root-created files with a simple user permision (and it wont work).

With sudo, erase the directory `/home/$username/.local/lib/python3.6/site-packages/lascar-1.1-py3.6.egg/` and try a ` python3 setup.py install --user` after that.
 
I think this should work.

**Comment by vincentdupaquis** [comment]
Hello,

I thank you for your solution, it effectively works.
I would btw recommend you put a caveat in you installation procedure as the conjonction of both sudo and --user put a terrible mess :-)

Best regards,
Vincent.
