### ISSUE TITLE
A line of RankProgressionOutputMethod's plot does not correspond to a single guess

### ISSUE THREAD

**Issue by blattm** [Ledger-Donjon/lascar#12]
Hello,

first of all, thank you for your work so far!

I tried to use the filters parameter to get RankProgressionOutputMethod to only output the rank of the solution, but the generated plot seemed to be incorrect. 

If I understand your source code correctly, a single line in a plot generated by RankProgressionOutputMethod (lets say line number k), will give you the answer to the question 'what is the k-th best guess?' and not 'what is the rank of guess k?'

The ScoreProgressionOutputMethod behaves in a similar way.

Is this intended behaviour? In case it is, it is there are two things that are rather confusing:
1) This behaviour is not documented.
2) When the solution is plotted, the line really gives you the rank of a single guess (working as I think it is intended)

Best,
Manuel

**Comment by yhql** [comment]
Hello, thanks for your report. Could you provide a script that reproduces the problem ?
I checked on the basic CPA example and the results seem correct.

Perhaps if you are working with an engine that does not have its `output_parser_mode` to `argmax` the plot will not mean much.

**Comment by manuelsanpedro** [comment]
Hello!

Ça roule la maintenance ??

**Comment by blattm** [comment]
Thank you for your answer.
Here is a short script:
```
from lascar import *
from lascar.tools.aes import sbox


container = BasicAesSimulationContainer(
    200, noise=2
)  # We use the BasicAesSimulationContainer with 2000 traces


guess_range = range(
    256
)

def generate_selection_function(byte):
    def selection_with_guess(
        value, guess
    ):  # selection_with_guess function must take 2 arguments: value and guess
        return hamming(sbox[value["plaintext"][byte] ^ guess])

    return selection_with_guess


cpa_engines = [
    CpaEngine(
        "cpa_%02d" % i,
        generate_selection_function(i),
        guess_range,
        solution=container.key[i],
    )
    for i in range(16)
]

session = Session(
    container,
    engines=cpa_engines,
    name="cpa on 16 bytes",
    output_method=[RankProgressionOutputMethod(*cpa_engines, filters=[[solution_guess] for solution_guess in container.key]),
                   RankProgressionOutputMethod(*cpa_engines)],
    output_steps=10,
).run(batch_size=50)

```

The preceding code is based on the provided cpa.py example. There are two RankProgressionOutputMethods. The first one sets a filter to only show the guesses corresponding to the real key. The second one doesn't set a filter. I believe the single lines from the first plot should be identical to the red solution lines in the second plot.

**Comment by yhql** [comment]
Thanks ! I see the problem. As you mentioned in your first issue : the `filters` parameter does not filter out keys, but rather points of the score array.

I'll replace this with a filter on key values. I don't think the current behaviour is useful in most cases.

**Comment by blattm** [comment]
Thanks!
In the meantime, I had a look at your code again, and I think I found out, what went wrong. So I created a pull request, which fixes the problem.

**Comment by yhql** [comment]
Thanks ! Looks fine. 

Fixed by https://github.com/Ledger-Donjon/lascar/commit/0a37b450cc635031492f88abbe2acef9983212d9
