### ISSUE TITLE
Recent Installation

### ISSUE THREAD

**Issue by eaerabi** [Ledger-Donjon/lascar#19]
Hi

I really appreciate your time to help me. 

I had Lascar on my older laptop which was working perfectly. 
On my new PC, I installed Python 3.7, 3.8.7 and 3.9 and the latest version of Lascar and I get this error: 

````

Session |N/A%|                          |0 trc/10000 | (3 engines, batch_size=500, leakage_shape=(26,)) |ETA:  --:--:--Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\eaerabi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\eaerabi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eaerabi\AppData\Roaming\Python\Python37\site-packages\lascar-1.1-py3.7.egg\lascar\engine\engine.py", line 82, in update
    self._update(batch)
  File "C:\Users\eaerabi\AppData\Roaming\Python\Python37\site-packages\lascar-1.1-py3.7.egg\lascar\engine\partitioner_engine.py", line 125, in new_update
    pcount, acc_x = jitted_update(batch.values, batch.leakages)
  File "c:\users\eaerabi\appdata\local\programs\python\python37\lib\site-packages\numba\core\dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "c:\users\eaerabi\appdata\local\programs\python\python37\lib\site-packages\numba\core\dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(array(uint32, 1d, C), bool)

There are 22 candidate implementations:
[1m  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(uint32, 1d, C), bool)':[0m
[1m   No match.[0m
[1m  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 162.
    With argument(s): '(array(uint32, 1d, C), bool)':[0m
[1m   Rejected as the implementation raised a specific error:
     TypeError: unsupported array index type bool in [bool][0m
  raised from c:\users\eaerabi\appdata\local\programs\python\python37\lib\site-packages\numba\core\typing\arraydecl.py:69
[0m
[0m[1mDuring: typing of intrinsic-call at C:\Users\eaerabi\AppData\Roaming\Python\Python37\site-packages\lascar-1.1-py3.7.egg\lascar\engine\partitioner_engine.py (116)[0m
[1m
File "..\..\..\Users\eaerabi\AppData\Roaming\Python\Python37\site-packages\lascar-1.1-py3.7.egg\lascar\engine\partitioner_engine.py", line 116:[0m
[1m            def jitted_update(batchvalues, batchleakages, pfunc = self._partition_function, psize = self._partition_size, rng2idx = self._partition_range_to_index, order = self._order):
                <source elided>
                for pv in np.arange(batchvalues.shape[0]):
[1m                    idx = rng2idx[pfunc(batchvalues[pv])]
[0m                    [1m^[0m[0m


````

These are the packages installed:
Package            Version
------------------ ----------
atomicwrites       1.4.0
attrs              20.3.0
cached-property    1.5.2
click              8.0.0a1
colorama           0.4.4
cycler             0.10.0
freetype-py        2.2.0
h5py               3.1.0
importlib-metadata 3.3.0
iniconfig          1.1.1
joblib             1.0.0
keras              2.4.3
kiwisolver         1.3.1
lascar             1.1
llvmlite           0.35.0
matplotlib         3.3.3
numba              0.52.0
numpy              1.20.0rc2
packaging          20.8
pillow             8.1.0
pip                20.1.1
pluggy             1.0.0.dev0
progressbar2       3.53.1
py                 1.10.0
pyparsing          3.0.0b2
pytest             6.2.1
python-dateutil    2.8.1
python-utils       2.4.0
pyyaml             5.3.1
scikit-learn       0.24.0
scipy              1.6.0
setuptools         47.1.0
six                1.15.0
sklearn            0.0
threadpoolctl      2.1.0
toml               0.10.2
typing-extensions  3.7.4.3
vispy              0.6.6
zipp               3.4.0

Thanks for your help. 
Regards
Ehsan

**Comment by yhql** [comment]
Hello,

from what I can see, numba does not know how to JIT the update function.
It seems you are using booleans as prediction values, can you try casting those into, say, `np.uint8` or `np.uint32` instead and see if helps ?

**Comment by eaerabi** [comment]
Thanks. 

Excellent! 
Actually, I just run the ttest.py example of Lascar which was working in the past. 

I changed the return value of the partition function from: 
` 
return value["plaintext"][byte] == 0
`

to 

`    if(value["plaintext"][byte] == 0):
        return 1
    else:
        return 0 
`
and now it works.
Thanks indeed!
Ehsan

**Comment by yhql** [comment]
Glad it's solved, thanks for the details !
