### ISSUE TITLE
'Dataset' object has no attribute 'value'

### ISSUE THREAD

**Issue by ddddavidee** [Ledger-Donjon/lascar#20]
In tutorial 8, https://github.com/Ledger-Donjon/lascar/blob/f928be7a579b2b748d4f181d46a80621b913b1ac/tutorial/08-session-manage-outputs.py#L161 the method `.value` is suggested to access a hdf5 dataset value. But the object has no such attribute.
```
  File "08-session-manage-outputs.py", line 161, in <module>
    assert np.all(hdf5_output_method_bis["dpa_lsb/500"].value == dpa_lsb_engine.finalize())
AttributeError: 'Dataset' object has no attribute 'value'
```

**Comment by adrianthillard** [comment]
Thank you for reporting this issue. We updated the tutorials by fixing numerous typos and this issue should also be resolved.

**Comment by ddddavidee** [comment]
(that works perfectly, thanks)
