### ISSUE TITLE
Missing requirement and Wrong arugment when using progressbar

### ISSUE THREAD

**Issue by Huanjia-Liu** [Ledger-Donjon/lascar#22]
Hey, found two issues. 
1. PYQT5 is needed when running 07-session-dpa-example.py to show the output result figure.
2. In ./lascar/session.py line 301. The "max_value" should be "maxval". Maybe it's about the version problem, my "progressbar" is version 2.5.

Regards,
-Huanjia

**Comment by adrianthillard** [comment]
Hello, thank you for your feedback.

We will add PyQt5 to the list of requirements.

For the progressbar issue, could you check that the progressbar2 library is installed? Last version should be 4.0.0.
```
python3 -m pip show progressbar2
Name: progressbar2
Version: 4.0.0
Summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
Home-page: https://github.com/WoLpH/python-progressbar
Author: Rick van Hattem (Wolph)
Author-email: wolph@wol.ph
License: BSD
```

Regards,
Adrian

**Comment by Huanjia-Liu** [comment]
Oh, mb, I still install progressbar rather than progressbar2. Thanks a lot.

**Comment by adrianthillard** [comment]
Ok cool, I'll close the issue.

Thank you very much for your feedback again.
